import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

self.skipWaiting();
clientsClaim();
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Notification Click Handler (Brings app to foreground and opens URL)
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window is already open, focus it and navigate
      for (const client of clientList) {
        if ('focus' in client) {
          if (client.url && !client.url.includes(urlToOpen)) {
            client.navigate(urlToOpen);
          }
          return client.focus();
        }
      }
      // Otherwise open new window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});

// Push Event Listener for Web Push API
self.addEventListener('push', (event) => {
  let data = { title: 'EduConnect', body: 'You have a new update!', icon: '/pwa-192x192.png', url: '/' };
  try {
    if (event.data) {
      data = event.data.json();
    }
  } catch {
    if (event.data) {
      data.body = event.data.text();
    }
  }

  const options = {
    body: data.body,
    icon: data.icon || '/pwa-192x192.png',
    badge: '/pwa-192x192.png',
    vibrate: data.vibrate || [300, 100, 300, 100, 300],
    data: { url: data.url || '/' },
    requireInteraction: data.requireInteraction || false,
    tag: data.tag || `edu-${Date.now()}`,
    actions: data.actions || [
      { action: 'open', title: 'Open EduConnect' }
    ]
  };

  event.waitUntil(self.registration.showNotification(data.title || 'EduConnect', options));
});
